name       : zfp
version    : 0.5.5
release    : 2
source     :
    - https://github.com/LLNL/zfp/releases/download/0.5.5/zfp-0.5.5.tar.gz : fdf7b948bab1f4e5dccfe2c2048fd98c24e417ad8fb8a51ed3463d04147393c5
homepage   : https://computing.llnl.gov/projects/floating-point-compression
license    : BSD-3-Clause
component  : programming.library
summary    : Compressed numerical arrays that support high-speed random access
description: |
    zfp is a compressed format for representing multidimensional floating-point and integer arrays. zfp provides compressed-array classes that support high throughput read and write random access to individual array elements. zfp also supports serial and parallel compression of whole arrays, e.g., for applications that read and write large data sets to and from disk.
builddeps  :
    - cython
    - numpy
setup      : |
    %cmake_ninja \
        -DCMAKE_SKIP_RPATH=ON \
        -DBUILD_CFP=ON \
        -DBUILD_ZFPY=ON \
        -DBUILD_ZFORP=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00755 solusBuildDir/bin/zfp $installdir/usr/bin/zfp
